javax:
    sql:
        DataSource:
            users-db:
                dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
                dataSource:
                    serverName: users-db
                    port: 3306
                    databaseName: users
                    user: users
                    password: pass
