#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
javax:
    sql:
        DataSource:
            users-db:
                dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
                dataSource:
                    serverName: users-db
                    port: 3306
                    databaseName: users
                    user: users
                    password: pass
